---@class LabelType
---@field CHAT_LOAD1 string
---@field TAB_PLAYER_DESCRIPTION string
---@field TAB_SERVER_SETTINGS_MODE_ARIZONA string
---@field COMMAND_ERROR string
---@field TAB_VEHICLE string
---@field TAB_SERVER_SETTINGS_AUTODETECT string
---@field TAB_SERVER_SETTINGS_CUSTOM_ERROR string
---@field COMMAND_EDIT string
---@field TAB_SERVER_SETTINGS_MODE_ARIZONA_ERROR string
---@field TAB_PLAYER string
---@field TAB_PLAYER_SETTINGS_BAR_HEIGHT string
---@field TAB_SERVER_SETTINGS_ARIZONA_SHOW_PLAYERS string
---@field SCALE string
---@field TAB_PLAYER_SETTINGS_BAR_OUTLINE_WIDTH string
---@field TAB_PLAYER_SETTINGS_DISPLAY_STAMINA string
---@field TAB_INFOBAR_SETTINGS_NEWLINE string
---@field FONTSCALE string
---@field TAB_SERVER_SETTINGS_ARIZONA_SHOW_SERVER string
---@field TAB_PLAYER_SETTINGS_BLINK_ON_LOW string
---@field TAB_VEHICLE_DESCRIPTION string
---@field TAB_PLAYER_SETTINGS_TITLE_BARS string
---@field TAB_SERVER_DESCRIPTION string
---@field TAB_PLAYER_SETTINGS_BAR_WIDTH string
---@field TAB_SERVER_LOGO string
---@field TAB_INFOBAR_SETTINGS_DATA string
---@field TAB_INFOBAR_SETTINGS_ICON string
---@field TAB_PLAYER_SETTINGS_DISPLAY_SATIETY string
---@field TAB_INFOBAR_SETTINGS_TEXT string
---@field TAB_INFOBAR_SETTINGS_SPACING string
---@field TAB_SERVER_SETTINGS_TITLE_MODE string
---@field TAB_INFOBAR string
---@field TAB_INFOBAR_DESCRIPTION string
---@field TAB_PLAYER_SETTINGS_MONEY_SEPARATOR string
---@field CHAT_LOAD2 string
---@field TAB_PLAYER_SETTINGS_DISABLE_GAME_HUD string
---@field TAB_PLAYER_SETTINGS_DISABLE_ARIZONA_HUD string
---@field TAB_SERVER_SETTINGS_MODE_NONE string
---@field ENABLE string
---@field TAB_SERVER_SETTINGS_MODE_CUSTOM string

---@type LabelType
Label = {} ---@diagnostic disable-line